name: Build Image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Docker image
        run: docker build -t beepsterr/discord.littlehelper --platform=linux/amd64 --progress=plain -f ./Dockerfile .

      - name: Push to package
        run: docker push beepsterr/discord.littlehelper