name: Build Image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/beepsterr/discord.steamlinker:${{ github.ref_name }} --platform=linux/amd64 --progress=plain -f ./Dockerfile .

      - name: Push to package
        run: docker push ghcr.io/beepsterr/discord.steamlinker:${{ github.ref_name }}