name: Build Image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/beepsterr/discord.littlehelper:${GITHUB_REF##*/} -f ./Dockerfile .

      - name: Push to package
        run: docker push ghcr.io/beepsterr/discord.littlehelper:${GITHUB_REF##*/}

      - name: Notify production of new build
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: "security_is_optional"